# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install libgtk-3-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Install dependencies
      run: |
        go get .

    - name: Build
      run: go build .

    - name: Compress
      run: tar -czvf ${{ github.event.repository.name }}.tar.gz ./firefox-profiles-selector install.sh config.ini icon.png

    - name: Upload built file
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.repository.name }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ${{ github.event.repository.name }}.tar.gz
          
